### ISSUE TITLE
Resource URL not found

### ISSUE THREAD

**Issue by cheasingh** [kzhovn/statusbar-pomo-obsidian#1]
this link return error 404 https://github.com/kzhovn/statusbar-pomo-obsidian/releases/download/0.0.3/manifest.json can't install from obisidian.

**Comment by kzhovn** [comment]
Yeah, I messed up setting up the files with the releases before 0.0.4. Does https://github.com/kzhovn/statusbar-pomo-obsidian/releases/tag/0.0.4 work for you?

**Comment by cheasingh** [comment]
thank @kzhovn, the link work fine and i can install it in obisidian. however the auto plugin install on obsidian plugin page still point to the 0.0.3 manifest as mention earlier.

**Comment by kzhovn** [comment]
Ought to be fixed now (0.0.5).
