### ISSUE TITLE
Add options for auto start of next pomo and break

### ISSUE THREAD

**Issue by TaqiyEddine-B** [kzhovn/statusbar-pomo-obsidian#13]
I suggest adding in the settings of this plugin the ability to activate/deactivate the auto start of next pomo and break. 

Another good suggestion is to specify the number of cycles of the auto pomo when the auto options are activated. As a user, I want to make a session of 4 pomos with breaks. After finishing this session, the auto option will stop automatically. This means that the auto option are enabled only for a specific number of cycles (cycle means : one pomo + one break)

**Comment by kzhovn** [comment]
For the second feature, were you imaging that the last cycle ends in a break or a pomodoro? (e.g. `pomo + break, ..., pomo + break` vs `pomo + break, .... , pomo`)

**Comment by TaqiyEddine-B** [comment]
I think that the last cycle should end with a break (short or long). Let's suppose that we have these values : 
   - auto_cycle = 4
   - auto_cycle_temp = auto_cycle 
   - long_break_interval  = 4 

Here is an example: 

- Cycle 1 -> The user start pomo 1 + AUTO START of short break  + updater()
- Cycle 2 -> AUTO START pomo 2 + AUTO START of short break  + updater()
- Cycle 3 -> AUTO START pomo 3 + AUTO START of short break  + updater()
- Cycle 4 -> AUTO START pomo 4 + AUTO START of **_long break_**  + updater()
- Now, the AUTO START option is automatically stopped until the user start a new cycle 
      
The default value of auto cycle in the settings could be equal to the number of Long break Interval. This option of auto cycle is only enabled when the auto start pomo and break options are enabled. Here is a pseudocode of the updater function:
```
 def updater() :
       auto_cycle_temp --
       if (auto_cycle_temp ==0):
                auto_cycle_temp = auto_cycle (the value from the settings)
```
I call this feature and these cycles "A Deep Work Session" when I try to focus on doing valuable and meaningful tasks of one unique project. I hope that other people find it useful

**Comment by kzhovn** [comment]
Done in 0.1.10, let me know if there are any issues!

**Comment by TaqiyEddine-B** [comment]
The new feature works well as expected. Thank you !
