### ISSUE TITLE
"Log to Daily Note" only points to the daily note at the time of toggling, then unsets itself

### ISSUE THREAD

**Issue by lepperm** [kzhovn/statusbar-pomo-obsidian#14]
Currently, if a user sets "Log to daily note" to true in settings, when we exit the settings screen and return, the "log file" field is populated with a hard link to today's note and "log to daily note" is unchecked.

1. Settings after updating to log to daily note:
![image](https://user-images.githubusercontent.com/12836873/128708557-560c6e71-ea80-4537-84f3-0041a164ba7c.png)

2. Settings upon exit and return to menu:
![image](https://user-images.githubusercontent.com/12836873/128708640-cf0930be-1eae-439d-83c3-54f1ec64e70e.png)

Expected behavior would be that "log to daily note" would remain checked after set by the user, and the target note receiving the log would always update to the latest day.

Currently, this requires me to return to settings and re-check "log to daily note" every day so that new pomos are linked at the bottom of today's note. (Love everything else though, this plugin is fantastic!)

**Comment by kzhovn** [comment]
Thanks for letting me know, should be fixed with 910859fbd5f13eadc4ed162782a21e7992966635.
