### ISSUE TITLE
Not installing on Mac 10.14.6 with obsidian 10.2.8

### ISSUE THREAD

**Issue by tristanbailey** [kzhovn/statusbar-pomo-obsidian#2]
Hi 
from the community tab in the app it does not install and gives the message in the alert that it failed. 

Not installing on Mac 10.14.6 with obsidian 10.2.8.

Happy to test if you have future releases.

tristan

**Comment by kzhovn** [comment]
Hey! I think this was just a version mismatch, I believe it should work now if you check for updates and then try again.
