### ISSUE TITLE
An issue regarding - Include link to note that was active at the moment timer started in the log

### ISSUE THREAD

**Issue by joellti** [kzhovn/statusbar-pomo-obsidian#21]
Just want to report that there is a corner case where it doesn't work as expected. Here is how I reproduce the issue.

- Configure the plugin as shown below
  - ![2021-10-03 19_15_48-N9700 - Obsidian v0 12 15](https://user-images.githubusercontent.com/77601108/135751380-3aa4cbc0-5981-4061-baac-8d37b815e44c.png)
  - ![image](https://user-images.githubusercontent.com/77601108/135754945-df9ed486-3a0e-4a14-a672-30d2ade0eff4.png)
- Restart Obsidian
- Go to a random note (I name it note 1)
- Start the timer and wait for the cycle to complete (I name it cycle 1)
- Go to a different note (I name it note 2)
- Start the timer and wait for the cycle to complete (I name it cycle 2)
- Go to the log file and find the entry for cycle 2. It shows the active note as note 1 instead of note 2

Another observation is that when the cycle 1 is complete, the count-down on the status bar stops as expected but the count-down number is one second past what's it's supposed to be. Maybe it's related to the issue I'm reporting.

**Comment by kzhovn** [comment]
Thanks for the bug report! Unfortunately this is linked to something where the best way to fix it would be to do a fairly significant refactor of the code (overdue anyway), which I don't currently have much time for. So I'm not sure when this will get fixed - is it significantly interfering with your workflow? I can try to patch it while I work on the underlying code issues, if so.

**Comment by kzhovn** [comment]
I'm on winter break now and finally have time to get to some of the bugs here; should be fixed now, but let me know if there are any further problems.
