### ISSUE TITLE
Add something to status bar time that shows whether on break or not.

### ISSUE THREAD

**Issue by GitMurf** [kzhovn/statusbar-pomo-obsidian#28]
I know it sounds crazy, but sometimes when I am working I get distracted and then come back to a timer and don't know if the time remaining is for a break or for the actual work time. Could you add something to the status bar when on break like appending a "b" or something so it would say 05:08 (b) to tell you its a break when 5 minutes and 8 seconds left in a break. Or something like this is signify a difference between a break and a regular timer.

**Comment by kzhovn** [comment]
Done in 0.1.13.
