### ISSUE TITLE
Add extra line break in log text otherwise they all clump together as one giant block of text with no empty line break

### ISSUE THREAD

**Issue by GitMurf** [kzhovn/statusbar-pomo-obsidian#29]
Add extra line break in log text otherwise they all clump together as one giant block of text with no empty line break.

If not by default, let the user add a `\n` to represent line breaks to add.

I want my timers to be able to be logged like:

```
Timer 1 stuff ....
<EMPTY LINE>
Timer 2 stuff ....
<EMPTY LINE>
etc.
```

Thanks!

**Comment by kzhovn** [comment]
Should be done in 0.1.13, just make sure you write `[\n]` so that it doesn't get formatted by moment.

**Comment by GitMurf** [comment]
Sorry I never responded to this but thanks a lot!
