### ISSUE TITLE
Status bar jumps – Could you use tabular numericals please?

### ISSUE THREAD

**Issue by Moonbase59** [kzhovn/statusbar-pomo-obsidian#3]
Apart from your really nice plugin I also use _Better word count_ which displays _left of your clock_ in the status bar and starts "hopping around" when the width of the clock numbers changes (like a "1" is smaller than "8"). This is really distracting, but there could be an easy fix:

Use _tabular nums_ for the clock in CSS, as in:

```css
font-variant-numeric: tabular-nums;
```

Think you could do that?

**Comment by kzhovn** [comment]
Hi! Thanks for the very helpful suggestion - I am completely unfamiliar with CSS and rather busy at the moment, but I'll add it as soon as I have a moment to figure out how to target the clock.

**Comment by kzhovn** [comment]
Ended up being much easier than expected, thanks for the specific fix suggestion @Moonbase59  :).

Ought to be all fixed if you update.
