### ISSUE TITLE
Give the option to void the pomodoro session

### ISSUE THREAD

**Issue by ontrou** [kzhovn/statusbar-pomo-obsidian#30]
An option to void (i.e. not log) the work session would be greatly appreciated. The idea is you have to complete a full pomodoro without interruptions, without pausing, without switching tasks or it doesn't count. Yes, I am hard core. Thank you so much for your plug in.

**Comment by kzhovn** [comment]
I'm not sure I understand the difference between the behavior you want and just running "start" or "quit" while another timer is running. Do you want to clear this timer _without_ starting a new timer, but also without completely quitting the pomodoro session?

**Comment by ontrou** [comment]
I set up a hotkey to quit the session, and then I use the mouse to click on the ribbon icon to start a new one. It's a little cumbersome to void/start sessions this way (compared with how easy it is to cycle through start-pause-start on the ribbon). But it is ok. I can live with it. Closing this issue.
