### ISSUE TITLE
TypeError: failed to execute 'appendChild' on 'Node'

### ISSUE THREAD

**Issue by mgmeyers** [kzhovn/statusbar-pomo-obsidian#4]
Hi there, it seems that this plugin is throwing an error about once a second:

<img width="715" alt="Screen Shot 2021-07-27 at 12 08 13 PM" src="https://user-images.githubusercontent.com/2694747/127213330-016957d0-cdda-4a99-af75-f785d11a2834.png">

This is happening when regardless of if the timer is running.

**Comment by kzhovn** [comment]
Huh, I'm not getting anything on my computer. Did this change between 0.1.1 and 0.1.2 (the latest version)?

**Comment by mgmeyers** [comment]
Not sure, I haven't opened dev tools in a while.

I imagine it's because of this:

https://github.com/kzhovn/statusbar-pomo-obsidian/blob/d83cb4a2029efb4c14b807792cd99f5fe6fe4bad/src/main.ts#L52-L53

When `this.mode` is `Mode.NoTimer`,  `setStatusBarText()` returns `undefined`. Seems like `setText` expects a value?

**Comment by kzhovn** [comment]
I've set it to return the empty string with this update - does that fix it for you?

**Comment by mgmeyers** [comment]
That did the trick, thanks!
