### ISSUE TITLE
Feature Request: Include link to note that was active at the moment timer started in the  log

### ISSUE THREAD

**Issue by andybyte** [kzhovn/statusbar-pomo-obsidian#6]
From the description it did not look like it does this, but it would be helpful if the log entry included a link to the note that was active at the moment the timer was started by the user. It can be a simple [[bracket link]] since it lives in Obsidian.

**Comment by kzhovn** [comment]
Thanks for the suggestion, should be there if you update. Let me know if there's any problems with it!
