### ISSUE TITLE
Feature : Can This Have Sound (White Background Noise)? 

### ISSUE THREAD

**Issue by grassbl8d** [kzhovn/statusbar-pomo-obsidian#7]
Hi,

Is it possible to add sound similar to how ticktick or forest does it ? 
A visual indicator would also help a lot. 

Thanks !

**Comment by grassbl8d** [comment]
Edited to reflect intention of white background noise. 

Thank You.

**Comment by kzhovn** [comment]
Hey! I don't know anything about ticktick or forest. Do you mean a background ticking noise to indicate that the clock's running, or something more like this https://www.youtube.com/watch?v=9oc8Fa7tb8c (to grab a random example)? If neither of these are the right idea, can you link me to an example sound file?

**Comment by grassbl8d** [comment]
Yeah ! Something like that. Great work btw. Sorry don't have sample files.

**Comment by kzhovn** [comment]
Having looked into it some more, I don't currently want to bundle the audio files with the plugin, they're pretty big and this isn't a central feature. I'll see if I can do it without that, but no promises, sorry.

**Comment by grassbl8d** [comment]
Maybe there's a way that it can be set to repeat to avoid large audio files ? Or possibly use a lower res sound file.

**Comment by grassbl8d** [comment]
HI, I added some sound and a merge request #8 

I'm not that familiar with typescript but hope I just used a free sound file from the internet and set it to repeat.

**Comment by grassbl8d** [comment]
Merged

**Comment by kzhovn** [comment]
The noise comes out quite loud -- can you regenerate that url somewhat quieter?

**Comment by grassbl8d** [comment]
Actually I just used this link 

https://base64.guru/converter/encode/audio

I actually prefer the sound to be loud so that it can drown out the noise in the house while I'm working from home.
